### ISSUE TITLE
3D Issues

### ISSUE THREAD

**Issue by DevShadd** [RSDuck/craftus_reloaded#4] opened 2017-09-02 22:11 UTC
I have two issues when I enable the 3D feature for Craftus: Reloaded.

1. If you walk into a block and then turn about 70-80 degrees to the left or right, you can see through the block through either your left or right eye (depending which side you turned).

2. If you walk up to a block, you can't see it because you cannot handle the 3D (When I get too close, I have to really do cross-eye 3D to see the block and it hurts to do it, but I don't like seeing the block not 3D either). The best way to fix this is to force the 3D mode to be unable to stick out any further than your eyes could handle (like when the camera gets really close to the blocks in Super Mario 3D Land).

**Comment by Auscobe** [comment] 2017-09-02 22:15
I can confirm these both working on the latest Stable release using my current house project in game.

**Comment by DevShadd** [comment] 2017-09-02 22:26
Left out one last thing: Crosshairs disappear when 3D gets enabled and reappears when 3D is turned back off.

**Comment by Auscobe** [comment] 2017-09-02 22:51
Oh Yeah i know about that. happens to me too.

**Comment by RSDuck** [comment] 2017-09-02 23:21
I'm aware of both issues. The thing with the 3d is easy to fix, but needs a lot of tinkering with different values, which is always boring, that's why I haven't done it yet :).

It is intended that the crosshair is hidden when 3d is turned on. 
The problem is that when the cross hair is nearer than the block you are looking at(which is almost always the case) it's really awkward to have the cross hair laying above the world, because you can't set your eye focus on one of both.
One option would be to set it exactly to the depth it's pointing at, but this isn't really practical, because it would have to be a normal plane, which intersects with the blocks and constantly jumps around, which looks also weird.
I when did some experiments with this, I considered just leaving it out and instead highlight the face of the block, you're looking at, additionally the best solution

**Comment by DevShadd** [comment] 2017-09-06 01:37
I can see why then. I just don't like the missing crosshair because I sometimes think I have to imagine one directly in the center when I place blocks, but then realize it highlights them for me. Thanks for answering anyway.

**Comment by RSDuck** [comment] 2017-11-12 16:36
the clipping issues are fixed in the latest in (pre) release

**Closed as completed by RSDuck** 2017-11-12 16:36 UTC
